const mongoose = require('mongoose')

let house = new mongoose.Schema({
    ' № ':                              {type: String},
    'Провайдер':                        {type: Array},
    'Идентификатор':                    {type: String},
    'Единый идентификатор дома':        {type: String},
    'ID других компаний':               {type: String},
    'Населенный пункт':                 {type: String},
    'Название улицы':                   {type: String},
    'Дом':                              {type: String},
    'Корпус':                           {type: String},
    'Мку':                              {type: String},
    'Этажей':                           {type: String},
    'Квартир':                          {type: String},
    'Технологии подключения дома':      {type: String},
    'Технологии подключения клиента':   {type: String},
    'Нестандартная нумерация':          {type: String},
    'Подъездов':                        {type: String},
    'Лифт':                             {type: String},
    'Признаки':                         {type: String},
    'Дата подключения дома':            {type: String},
    'Дата тв':                          {type: String},
    'Дата интернет':                    {type: String},
    'Дом в монтаже с':                  {type: String},
    'Cлаботочка в подъездах':           {type: String},
    'Обслуживающая организация':        {type: String},
    'Комментарий согласователей':       {type: String},
    'Примечание':                       {type: String},
    'Перекид с':                        {type: String},
    'Микрорайон':                       {type: String},
    'Почтовое отделение':               {type: String},
    'Индекс':                           {type: String},
    'Адрес':                            {type: String},
    'Широта':                           {type: String},
    'Долгота':                          {type: String},
    'Номер Зоны Wi-Fi (число)':         {type: String},
    'Признак другого оператора':        {type: String},
    'Потенциальная зона подключения':   {type: String},
    'Год постройки здания':             {type: String},
    'Код ФИАС':                         {type: String}    
})
module.exports = mongoose.model('Houses', house)
